const SearchReducerType = Object.freeze({
    NAME_CONFIGURED: 0,
    PRICE_CONFIGURED: 1,
    MARKET_CONFIGURED: 2,
    ORDER_CONFIGURED: 3,
    PAGE_CONFIGURED: 4,
    GET_SUMMARY: 5,
    PRODUCTS_SEARCHED: 6,
    PRODUCTS_SELECTED: 7,
    PRODUCTS_UNSELECTED: 8,
    GET_PRODUCTS: 9,
    SEARCHBAR_STATE_CHANGED: 10,
    PRODUCTS_LOADED_MORE: 11
});

export default SearchReducerType;